#index:
#  path: /
#  controller: App\Controller\HelloWorldController::index
#records:
#  path: /record
#  controller: App\Controller\RecordController::index
#tasks:
#  path: /tasks
#  controller: App\Controller\TaskController::index
##show:
##  path: /{id}
##  controller: App\Controller\RecordController::show
#category_index:
#  path: /category/index
#  controller: App\Controller\CategoryController::index
#category_create:
#  path: /category/create
#  controller: App\Controller\CategoryController::create
#category_edit:
#  path: /category/{id}/edit
#  controller: App\Controller\CategoryController::edit
#category_delete:
#  path: /category/{id}/delete
#  controller: App\Controller\CategoryController::delete
